import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import apiServices from "../services/ApiServices";
import { useEffect, useState } from "react";
import Loader from "../components/Loader";
import { useDispatch, useSelector } from "react-redux";
import { setMergedData } from "../redux/actions/staticBarActions";
import Cards from "../components/Cards";
import { Col, Row, Typography } from "antd";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const mergeData = useSelector((state) => state.staticBar.data);
  const dispatch = useDispatch();

  console.log("data", mergeData);

  const [loading, setloading] = useState(false);

  useEffect(() => {
    // getValues();
    setloading(true);
    dispatch(setMergedData);
  }, [dispatch]);

  let l;
  // console.log("data", data);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">
        {!loading && <Loader />}
        <Typography.Title level={2} style={{
          color: "white",
          textAlign: "center"
        }}>Blogs</Typography.Title>
        <div className="main-cards">
          <Row gutter={[16,16]}>
          {loading &&
            mergeData?.length > 0 &&
            mergeData.map((item, index) => <Col sm={24} xs={24} md={8} lg={8} xl={8} key={index}>
            <Cards  item={item}/>
            </Col>
            )}
          </Row>
         
        </div>
      </main>
    </>
  );
}
